version: "2"
services: 
  app:
    build: ./
    links: 
      - db
    ports: 
      - "8000:5000"
  db:
    image: mysql:5.7
    ports: 
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: user 
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    